In [1]:
import numpy as np

In [2]:
array1= np.arange(10)

In [3]:
array1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array1[5]

5

In [5]:
array1[0:4]

array([0, 1, 2, 3])

In [6]:
array1[0:4]=10

In [7]:
array1

array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9])

In [8]:
slice_of_arr=array1[2:5]


In [9]:
slice_of_arr

array([10, 10,  4])

In [10]:
array1

array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9])

In [11]:
slice_of_arr[:]=55


In [12]:
slice_of_arr
array1

array([10, 10, 55, 55, 55,  5,  6,  7,  8,  9])

In [13]:
slice_of_arr

array([55, 55, 55])

In [14]:
slice_of_arr

array([55, 55, 55])

In [15]:
array


NameError: name 'array' is not defined

In [16]:
array1

array([10, 10, 55, 55, 55,  5,  6,  7,  8,  9])

In [19]:
slice_of_arr2=array1[5:8]

In [20]:
slice_of_arr2[:]=77
slice_of_arr

array([55, 55, 55])

In [21]:
array1

array([10, 10, 55, 55, 55, 77, 77, 77,  8,  9])

In [23]:
slice_of_arr

array([55, 55, 55])

In [24]:
slice_of_arr2

array([77, 77, 77])

In [26]:
multi_array=np.array(([1,2,3,4],[5,6,7,8]))

In [27]:
multi_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
multi_array[0]

array([1, 2, 3, 4])

In [29]:
multi_array[1][2]

7

In [30]:
multi_array[:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [31]:
multi_array[1:2,0:1]

array([[5]])

In [32]:
array_2d=np.zeros((4,4))

In [33]:
array_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
arr_length= array_2d.shape[1]

In [39]:
arr_length

4

In [41]:
array_2d.shape


(4, 4)

In [45]:
for i in range(arr_length):
    array_2d[i]=3

In [46]:
array_2d

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])