In [1]:
import numpy as np

In [2]:
arr=np.arange(50).reshape((10,5))

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [4]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [6]:
array=np.array(([1,2,3],[4,5,6]))

In [7]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
array.swapaxes(0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
 website='http://google.com'
import webbrowser
webbrowser.open(website)

True