In [1]:
import numpy as np

In [2]:
5/2

2.5

In [4]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])

In [5]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr1 * arr1


array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [7]:
arr1/arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
arr1*2


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [9]:
arr1 * 3

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24]])

In [10]:
arr1 **3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)