In [11]:
import numpy as np

In [5]:
my_list1 = [1,2,3,4]

In [6]:
my_array1= np.array(my_list1)

In [7]:
my_array1

array([1, 2, 3, 4])

my_list2 =[11,22,33,44]

In [8]:
my_list2 =[11,22,33,44]

In [9]:
my_lists=[my_list1, my_list2]

In [10]:
my_array2= np.array(my_lists)

NameError: name 'np' is not defined

In [11]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [12]:
 my_array2.shape

(2, 4)

In [13]:
my_array2.dtype

dtype('int32')

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
my_zeros_Array= np.zeros(5)

In [16]:
my_zeros_aray.dtype

NameError: name 'my_zeros_aray' is not defined

In [17]:
my_zeros_array.dtype


NameError: name 'my_zeros_array' is not defined

In [18]:
print "Hello"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Hello")? (<ipython-input-18-dabf489e9f92>, line 1)

In [19]:
print("Hello")

Hello


In [1]:
5/2

2.5

In [1]:
test_list=[1,2,3]

In [2]:
test_list=[1,2,3,4]

In [3]:
print test_list


SyntaxError: Missing parentheses in call to 'print'. Did you mean print(test_list)? (<ipython-input-3-ceff35ed2d36>, line 1)

In [4]:
print (test_list)

[1, 2, 3, 4]


In [5]:
test_list_new=[1,2,3]

In [6]:
multi_list=[test_list, test_list_new]

In [7]:
print(multi_list)

[[1, 2, 3, 4], [1, 2, 3]]


In [8]:
multi_list.shape

AttributeError: 'list' object has no attribute 'shape'

In [12]:
array=np.array(multi_list)

In [13]:
array.shape

(2,)

In [14]:
array.dtype

dtype('O')

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.arange(2)

array([0, 1])

In [18]:
np.arange(5,45,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40])